#include "mbed.h"
#include "PinDetect.h"
#include "uLCD_4DGL.h"
#include "SDFileSystem.h"
#include <iostream>
#include <string>
#include <cmath>

SDFileSystem sd(p5, p6, p7, p8, "sd");

PinDetect pb1(p18); //pushbuttons
PinDetect pb2(p19);
PinDetect pb3(p20);

uLCD_4DGL uLCD(p28, p27, p29);

enum InputType {YES, NO, NOT_PRESSED, DEC};
//enum StateType {WAIT, COPY, END};
enum StateType {WAIT, ENCODE, HIGH, LOW};

InputType input = NOT_PRESSED;
StateType state = WAIT;
//---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pb1 hit
// That is ... this code runs with interrupt is generated by first button press
void pb1_hit_callback (void)
{

    input = YES;
}

// ---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pb2 hit
// That is ... this code runs with interrupt is generated by second button press
void pb2_hit_callback (void)
{
    input = NO;
}

// ---------------------------------------------------------------------------------------------------
// Callback routine is interrupt activated by a debounced pb3 hit
// That is ... this code runs with interrupt is generated by third button press
void pb3_hit_callback (void)
{

    input = DEC;
}


string arrayCipher; //1000 character key
int position; //position in key

//read key in cipher
void readCipher()
{

    FILE *fp = fopen("/sd/mydir/OTP.txt", "r");
    if(fp == NULL) {
        uLCD.printf("Open Error!!!\n");
    } else {
        fscanf(fp, "%s",arrayCipher);
    }
    fclose(fp);
}

//read position in sender position file
void readPos()
{
    FILE *fp2 = fopen("/sd/mydir/positionCipherSender.txt", "r");
    if(fp2 == NULL) {
        uLCD.printf("Open Error!!!\n");
    } else {
        fscanf(fp2, "%i",&position);
        fclose(fp2);
    }
}

// write position in sender position file
void writePos()
{
    mkdir("/sd/mydir", 0777);
    FILE *fp2 = fopen("/sd/mydir/positionCipherSender.txt", "w+");
    if(fp2 == NULL) {
        uLCD.printf("Error Open\n");
    } else {
        fprintf(fp2, "%i", position+1) ; //write line
    }
    fclose(fp2);
}

//prints current letter in alphabet
void printCurrentLetter(char currLetter)
{
    uLCD.locate(0,0);
    uLCD.text_width(5);
    uLCD.text_height(5);
    uLCD.printf("%c",currLetter);
}


//converts int to char
char toChar(int x)
{
    x = x % 26;
    char letter = char('A' + x);
    return letter;
}

// ---------------------------------------------------------------------------------------------------
int main()
{
    //setup push buttons
    pb1.mode(PullUp);
    pb2.mode(PullUp);
    pb3.mode(PullUp);

    // Delay for initial pullup to take effect
    wait(.01);

    // Setup Interrupt callback functions for a pb hit
    pb1.attach_deasserted(&pb1_hit_callback);
    pb2.attach_deasserted(&pb2_hit_callback);
    pb3.attach_deasserted(&pb3_hit_callback);

    // Start sampling pb inputs using interrupts
    pb1.setSampleFrequency();
    pb2.setSampleFrequency();
    pb3.setSampleFrequency();

    //generate one type pad


    bool getout = false;
    // pushbuttons now setup and running




    int counter = 0; //counter for alphabet
    string abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; //string of alphabet
    readCipher();
    while(!getout) {
        wait(0.1);
        switch(state) {
            case (HIGH):
                //move up in the alphabet
                counter = (counter + 1) % 26;
                printCurrentLetter(abc[counter]);
                state = WAIT;

                //calculate next state
                break;
            case (WAIT):
                //calculate the next state
                if (input == YES) {
                    state = HIGH;
                    input = NOT_PRESSED;
                } else if (input == NO) {
                    state = LOW;
                    input = NOT_PRESSED;
                } else if (input == DEC) {
                    state = ENCODE;
                    input = NOT_PRESSED;
                    break;
                case (LOW):
                    //move down in the alphabet
                    counter = (counter - 1);
                    if (counter < 0) {
                        counter = 25;
                    }
                    printCurrentLetter(abc[counter]);
                    state = WAIT;
                    break;
                case (ENCODE):
                    //encode current letter
                    readPos();
                    uLCD.locate(0,2);
                    uLCD.text_width(5);
                    uLCD.text_height(5);
                    char letter2 = toChar(arrayCipher[position] + abc[counter]);
                    uLCD.printf("%c", letter2);
                    writePos();
                    state = WAIT;

                    break;

                } //end of switch statement

        } //end while loop
    }
} //end main